# -*- coding: utf-8 -*-
"""dev_assg.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19zha1iy2kyxv0ZmewLuqWKcBFNg4diof
"""

import pandas as pd

df = pd.read_csv('/content/event_log.csv')

df.head()

df.head

df.columns  = [c.replace(' ','_') for c in df.columns]

type(df.Task_Category.value_counts())

a = df.Task_Category.value_counts()

df_noe = a.to_frame()

df_noe

df_noe

l1 = df_noe.reset_index().values.tolist()

l1

len(l1)

import csv
f = open('Task_Category.csv', 'w')
header = ['Task','count']
writer = csv.writer(f)
writer.writerow(header)
for i in l1:
  writer.writerow(i)
f.close()

df11 = pd.read_csv('/content/Task_Category.csv')

df11.head()

l2 = []
l2 = df['Level'].to_list()
l2

l2[12908]

import csv
f = open('date_and_time.csv', 'w')
header = ['date_and_time']
writer = csv.writer(f)
writer.writerow(header)
for i in l2:
  l = [i]
  writer.writerow(l)
f.close()

df3 = pd.read_csv('/content/date_and_time.csv',on_bad_lines='skip')

df3.head()